name: cine_practica
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  google_fonts: ^6.2.1
  table_calendar: ^3.0.0
  firebase_core: ^2.31.1
  firebase_database: ^10.5.6
  http: ^1.2.1
  intl: ^0.17.0
  date_format: ^2.0.0
  
  

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.png
    - assets/background2.png
    - assets/running1.png
    - assets/resistencia.png
    - assets/resistenciaAvanzada.png

fonts:
  - family: Philosopher
    fonts:
      - asset: Philosopher/Philosopher-Regular.ttf
      - asset: Philosopher/Philosopher-Italic.ttf
        style: italic
